import "./globals.css";
import CookieConsentBanner from "./components/cookies";

export const metadata = {
  title: 'Steuerberatung am Rathaus',
  description: 'Generated by Next.js',
  icons: {
    icon: '/favicon.ico',
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="de">
       
      <body>
        <CookieConsentBanner />
        {children}
        </body>
    </html>
  )
}
